export enum INTERVIEW_ROUND_STATUS {
	SCHEDULED = "SCHEDULED",
	RESCHEDULED = "RESCHEDULED",
	COMPLETED = "COMPLETED",
	CANCELLED = "CANCELLED",
	NO_SHOW = "NO_SHOW",
}

export enum CANDIDATE_CONFIRMATION_STATUS {
	PENDING = "PENDING",
	CONFIRMED = "CONFIRMED",
	DECLINED = "DECLINED",
}

export enum CANDIDATE_INTERVIEW_STATUS {
	PENDING = "PENDING",
	PASS = "PASS",
	REJECTED = "REJECTED",
}
