export const AUTH_RECRUITER_TOKEN = {
	RECRUITER_LOGIN_USE_CASE: "RECRUITER_LOGIN_USE_CASE",
	RECRUITER_REGISTER_USE_CASE: "RECRUITER_REGISTER_USE_CASE",
	RECRUITER_REFRESH_USE_CASE: "RECRUITER_REFRESH_USE_CASE",
	RECRUITER_LOGOUT_USE_CASE: "RECRUITER_LOGOUT_USE_CASE",
	RECRUITER_VERIFY_OTP_USE_CASE: "RECRUITER_VERIFY_OTP_USE_CASE",
} as const;
