export const RECRUITER_TOKEN = {
	RECRUITER_CREATE_USE_CASE: "RECRUITER_CREATE_USE_CASE",
	RECRUITER_GET_ALL_USE_CASE: "RECRUITER_GET_ALL_USE_CASE",
	RECRUITER_GET_ONE_USE_CASE: "RECRUITER_GET_ONE_USE_CASE",
	RECRUITER_UPDATE_USE_CASE: "RECRUITER_UPDATE_USE_CASE",
	RECRUITER_BLOCK_UNBLOCK_USE_CASE: "RECRUITER_BLOCK_UNBLOCK_USE_CASE",
	RECRUITER_CHANGE_PASSWORD_USE_CASE: "RECRUITER_CHANGE_PASSWORD_USE_CASE",
	RECRUITER_REPOSITORY: "RECRUITER_REPOSITORY",
	CHECK_RECRUITER_BLOCKED_USE_CASE: "CHECK_RECRUITER_BLOCKED_USE_CASE",
	UPLOAD_PROFILE_IMAGE_USE_CASE: "UPLOAD_PROFILE_IMAGE_USE_CASE",
} as const;
