import type { FormConfigCreateData } from "@/domain/types/form-config-data.type";

/**
 * Seed definitions for admin-configurable forms. Each entry is upserted on
 * startup only when it does not already exist, so admin edits are never
 * overwritten. Locked fields are structural and cannot be disabled or removed.
 */
export const DEFAULT_FORMS: FormConfigCreateData[] = [
	{
		formKey: "candidate.signup",
		name: "Candidate signup",
		audience: "candidate",
		fields: [
			{
				key: "name",
				label: "Full name",
				type: "text",
				placeholder: "Jane Cooper",
				required: true,
				enabled: true,
				locked: true,
				custom: false,
				order: 0,
			},
			{
				key: "email",
				label: "Email address",
				type: "email",
				placeholder: "you@example.com",
				required: true,
				enabled: true,
				locked: true,
				custom: false,
				order: 1,
			},
			{
				key: "phone",
				label: "Phone number",
				type: "tel",
				placeholder: "+1 (555) 000-0000",
				required: false,
				enabled: true,
				locked: false,
				custom: false,
				order: 2,
			},
			{
				key: "password",
				label: "Password",
				type: "password",
				placeholder: "Create a password",
				required: true,
				enabled: true,
				locked: true,
				custom: false,
				order: 3,
			},
			{
				key: "confirmPassword",
				label: "Confirm password",
				type: "password",
				placeholder: "Re-enter your password",
				required: true,
				enabled: true,
				locked: true,
				custom: false,
				order: 4,
			},
		],
	},
	{
		formKey: "auth.login",
		name: "Login",
		audience: "auth",
		fields: [
			{
				key: "email",
				label: "Email address",
				type: "email",
				placeholder: "you@example.com",
				required: true,
				enabled: true,
				locked: true,
				custom: false,
				order: 0,
			},
			{
				key: "password",
				label: "Password",
				type: "password",
				placeholder: "Your password",
				required: true,
				enabled: true,
				locked: true,
				custom: false,
				order: 1,
			},
		],
	},
	{
		formKey: "auth.otp",
		name: "OTP verification",
		audience: "auth",
		fields: [
			{
				key: "otp",
				label: "Verification code",
				type: "text",
				placeholder: "Enter the 6-digit code",
				required: true,
				enabled: true,
				locked: true,
				custom: false,
				order: 0,
			},
		],
	},
	{
		formKey: "auth.forgot-password",
		name: "Forgot password",
		audience: "auth",
		fields: [
			{
				key: "email",
				label: "Email address",
				type: "email",
				placeholder: "you@example.com",
				required: true,
				enabled: true,
				locked: true,
				custom: false,
				order: 0,
			},
		],
	},
	{
		formKey: "auth.reset-password",
		name: "Reset password",
		audience: "auth",
		fields: [
			{
				key: "password",
				label: "New password",
				type: "password",
				placeholder: "Create a new password",
				required: true,
				enabled: true,
				locked: true,
				custom: false,
				order: 0,
			},
			{
				key: "confirmPassword",
				label: "Confirm new password",
				type: "password",
				placeholder: "Re-enter your new password",
				required: true,
				enabled: true,
				locked: true,
				custom: false,
				order: 1,
			},
		],
	},
	{
		formKey: "candidate.profile-basic",
		name: "Basic information",
		audience: "candidate",
		fields: [
			{
				key: "name",
				label: "Full name",
				type: "text",
				placeholder: "e.g. Uday Krishna",
				required: true,
				enabled: true,
				locked: false,
				custom: false,
				order: 0,
				minLength: 2,
			},
			{
				key: "tagline",
				label: "Professional tagline",
				type: "text",
				placeholder: "e.g. Senior Frontend Engineer",
				required: true,
				enabled: true,
				locked: false,
				custom: false,
				order: 1,
				minLength: 2,
			},
			{
				key: "location",
				label: "Location",
				type: "text",
				placeholder: "e.g. Kochi, Kerala, India",
				required: false,
				enabled: true,
				locked: false,
				custom: false,
				order: 2,
			},
			{
				key: "phone",
				label: "Phone number",
				type: "tel",
				placeholder: "e.g. +91 9876543210",
				required: false,
				enabled: true,
				locked: false,
				custom: false,
				order: 3,
			},
			{
				key: "bio",
				label: "Bio",
				type: "textarea",
				placeholder: "Tell recruiters about yourself...",
				required: false,
				enabled: true,
				locked: false,
				custom: false,
				order: 4,
			},
			{
				key: "experience",
				label: "Years of experience",
				type: "text",
				placeholder: "e.g. 3 years in frontend development",
				required: false,
				enabled: true,
				locked: false,
				custom: false,
				order: 5,
			},
			{
				key: "linkedin",
				label: "LinkedIn profile link",
				type: "url",
				placeholder: "https://linkedin.com/in/username",
				required: false,
				enabled: true,
				locked: false,
				custom: false,
				order: 6,
			},
			{
				key: "portfolio",
				label: "Personal portfolio link",
				type: "url",
				placeholder: "https://myportfolio.com",
				required: false,
				enabled: true,
				locked: false,
				custom: false,
				order: 7,
			},
			{
				key: "github",
				label: "GitHub profile link",
				type: "url",
				placeholder: "https://github.com/username",
				required: false,
				enabled: true,
				locked: false,
				custom: false,
				order: 8,
			},
		],
	},
	{
		formKey: "candidate.job-preferences",
		name: "Job preferences",
		audience: "candidate",
		fields: [
			{
				key: "jobTypes",
				label: "Preferred job types",
				type: "select",
				required: false,
				enabled: true,
				locked: false,
				custom: false,
				order: 0,
				options: [
					{ label: "Full-time", value: "Full-time" },
					{ label: "Part-time", value: "Part-time" },
					{ label: "Internship", value: "Internship" },
					{ label: "Contract", value: "Contract" },
					{ label: "Freelance", value: "Freelance" },
				],
			},
			{
				key: "roles",
				label: "Preferred roles (comma separated)",
				type: "text",
				placeholder: "e.g. Frontend Engineer, Full Stack Developer",
				required: true,
				enabled: true,
				locked: false,
				custom: false,
				order: 1,
			},
			{
				key: "workStyles",
				label: "Work styles",
				type: "select",
				required: false,
				enabled: true,
				locked: false,
				custom: false,
				order: 2,
				options: [
					{ label: "Remote", value: "Remote" },
					{ label: "Hybrid", value: "Hybrid" },
					{ label: "On-site", value: "On-site" },
				],
			},
			{
				key: "currency",
				label: "Currency",
				type: "select",
				required: false,
				enabled: true,
				locked: false,
				custom: false,
				order: 3,
				options: [
					{ label: "USD", value: "USD" },
					{ label: "INR", value: "INR" },
					{ label: "EUR", value: "EUR" },
				],
			},
			{
				key: "salaryFrequency",
				label: "Salary period",
				type: "select",
				required: false,
				enabled: true,
				locked: false,
				custom: false,
				order: 4,
				options: [
					{ label: "Yearly", value: "yearly" },
					{ label: "Monthly", value: "monthly" },
					{ label: "Hourly", value: "hourly" },
				],
			},
			{
				key: "minSalary",
				label: "Minimum salary",
				type: "number",
				placeholder: "Min",
				required: false,
				enabled: true,
				locked: false,
				custom: false,
				order: 5,
			},
			{
				key: "maxSalary",
				label: "Maximum salary",
				type: "number",
				placeholder: "Max",
				required: false,
				enabled: true,
				locked: false,
				custom: false,
				order: 6,
			},
		],
	},
	{
		formKey: "candidate.education",
		name: "Education",
		audience: "candidate",
		fields: [
			{
				key: "level",
				label: "Education level",
				type: "select",
				required: true,
				enabled: true,
				locked: false,
				custom: false,
				order: 0,
				options: [
					{ label: "School", value: "School" },
					{ label: "High School", value: "High School" },
					{ label: "Graduate", value: "Graduate" },
					{ label: "Post Graduate", value: "Post Graduate" },
					{ label: "PhD", value: "PhD" },
					{ label: "Other", value: "Other" },
				],
			},
			{
				key: "school",
				label: "Institution / school name",
				type: "text",
				placeholder: "e.g. Stanford University",
				required: true,
				enabled: true,
				locked: false,
				custom: false,
				order: 1,
			},
			{
				key: "degree",
				label: "Degree",
				type: "text",
				placeholder: "e.g. Bachelor of Science",
				required: true,
				enabled: true,
				locked: false,
				custom: false,
				order: 2,
			},
			{
				key: "specialisation",
				label: "Specialisation",
				type: "text",
				placeholder: "e.g. Computer Science",
				required: true,
				enabled: true,
				locked: false,
				custom: false,
				order: 3,
			},
			{
				key: "startDate",
				label: "Start date",
				type: "date",
				required: false,
				enabled: true,
				locked: false,
				custom: false,
				order: 4,
			},
			{
				key: "endDate",
				label: "End date",
				type: "date",
				required: false,
				enabled: true,
				locked: false,
				custom: false,
				order: 5,
			},
		],
	},
	{
		formKey: "candidate.experience",
		name: "Experience",
		audience: "candidate",
		fields: [
			{
				key: "title",
				label: "Job title",
				type: "text",
				placeholder: "e.g. Senior Backend Developer",
				required: true,
				enabled: true,
				locked: false,
				custom: false,
				order: 0,
			},
			{
				key: "role",
				label: "Job role",
				type: "select",
				required: false,
				enabled: true,
				locked: false,
				custom: false,
				order: 1,
				options: [
					{ label: "Frontend", value: "Frontend" },
					{ label: "Backend", value: "Backend" },
					{ label: "Full-stack", value: "Full-stack" },
					{ label: "DevOps", value: "DevOps" },
					{ label: "UI/UX", value: "UI/UX" },
				],
			},
			{
				key: "description",
				label: "Description",
				type: "textarea",
				placeholder: "Enter job description...",
				required: true,
				enabled: true,
				locked: false,
				custom: false,
				order: 2,
			},
			{
				key: "company",
				label: "Company name",
				type: "text",
				placeholder: "e.g. Google",
				required: true,
				enabled: true,
				locked: false,
				custom: false,
				order: 3,
			},
			{
				key: "location",
				label: "Location / address",
				type: "text",
				placeholder: "e.g. Mountain View, CA",
				required: true,
				enabled: true,
				locked: false,
				custom: false,
				order: 4,
			},
			{
				key: "industry",
				label: "Industry",
				type: "select",
				required: false,
				enabled: true,
				locked: false,
				custom: false,
				order: 5,
				options: [
					{ label: "Technology", value: "Technology" },
					{ label: "Finance", value: "Finance" },
					{ label: "Healthcare", value: "Healthcare" },
					{ label: "Education", value: "Education" },
					{ label: "E-commerce", value: "E-commerce" },
				],
			},
			{
				key: "currentlyWorking",
				label: "Currently working here",
				type: "select",
				required: false,
				enabled: true,
				locked: false,
				custom: false,
				order: 6,
				options: [
					{ label: "Yes", value: "yes" },
					{ label: "No", value: "no" },
				],
			},
			{
				key: "employmentType",
				label: "Employment type",
				type: "select",
				required: false,
				enabled: true,
				locked: false,
				custom: false,
				order: 7,
				options: [
					{ label: "Full-time", value: "Full-time" },
					{ label: "Part-time", value: "Part-time" },
					{ label: "Intern", value: "Intern" },
					{ label: "Contract", value: "Contract" },
				],
			},
			{
				key: "noticePeriod",
				label: "Notice period",
				type: "select",
				required: false,
				enabled: true,
				locked: false,
				custom: false,
				order: 8,
				options: [
					{ label: "No notice period", value: "No notice period" },
					{ label: "Less than 15 days", value: "Less than 15 days" },
					{ label: "1 month", value: "1 month" },
					{ label: "2 months", value: "2 month" },
					{ label: "3 or more months", value: "3 or more months" },
				],
			},
			{
				key: "startDate",
				label: "Start date",
				type: "date",
				required: false,
				enabled: true,
				locked: false,
				custom: false,
				order: 9,
			},
			{
				key: "endDate",
				label: "End date",
				type: "date",
				required: false,
				enabled: true,
				locked: false,
				custom: false,
				order: 10,
			},
		],
	},
	{
		formKey: "candidate.certificate",
		name: "Certificate",
		audience: "candidate",
		fields: [
			{
				key: "name",
				label: "Certificate name",
				type: "text",
				placeholder: "e.g. AWS Solution Architect",
				required: true,
				enabled: true,
				locked: false,
				custom: false,
				order: 0,
			},
			{
				key: "issuer",
				label: "Issuing organization",
				type: "text",
				placeholder: "e.g. Amazon Web Services",
				required: true,
				enabled: true,
				locked: false,
				custom: false,
				order: 1,
			},
			{
				key: "issueDate",
				label: "Date earned",
				type: "date",
				required: false,
				enabled: true,
				locked: false,
				custom: false,
				order: 2,
			},
		],
	},
	{
		formKey: "candidate.language",
		name: "Language",
		audience: "candidate",
		fields: [
			{
				key: "name",
				label: "Language name",
				type: "text",
				placeholder: "Search or type language...",
				required: true,
				enabled: true,
				locked: false,
				custom: false,
				order: 0,
			},
			{
				key: "level",
				label: "Proficiency level",
				type: "select",
				required: true,
				enabled: true,
				locked: false,
				custom: false,
				order: 1,
				options: [
					{ label: "Native", value: "Native" },
					{ label: "C2 Expert", value: "C2" },
					{ label: "C1 Advanced", value: "C1" },
					{ label: "B2 Upper-Int", value: "B2" },
					{ label: "B1 Basic", value: "B1" },
				],
			},
		],
	},
];
