export const PLAN_LIMITS = {
	FREE: {
		MAX_CERTIFICATES: 20,
		MAX_EDUCATION: 20,
		MAX_PROJECTS: 20,
		MAX_ADDRESSES: 5,
	},
	PREMIUM: {
		MAX_CERTIFICATES: 50,
		MAX_EDUCATION: 50,
		MAX_PROJECTS: 50,
		MAX_ADDRESSES: 10,
	},
};
