export enum USER_AUTH_ROUTER {
	DEFAULT = "/",
	LOGIN = "/login",
	SIGNUP = "/signup",
	REFRESH = "/refresh",
	ROUTER = "auth/user",
	OTP_RESEND = "/resend-otp",
	OTP = "/otp",
	FORGOT_PASSWORD = "/forgot-password",
	OTP_VERIFY = "/otp-verify",
	GOOGLE = "/google",
	LOGOUT = "logout",
	RESET_PASSWORD = "/reset-password",
	VERIFY_RESET_TOKEN = "/verify-reset-token",
	CSRF = "/csrf-token",
}
