export enum ADDRESS_TOKEN {
	ADDRESS_REPOSITORY = "ADDRESS_REPOSITORY",
	CREATE_ADDRESS_USE_CASE = "CREATE_ADDRESS_USE_CASE",
	GET_ADDRESSES_USE_CASE = "GET_ADDRESSES_USE_CASE",
	UPDATE_ADDRESS_USE_CASE = "UPDATE_ADDRESS_USE_CASE",
	DELETE_ADDRESS_USE_CASE = "DELETE_ADDRESS_USE_CASE",
}
