export enum ADMIN_AUTH_TOKEN {
    ADMIN_LOGIN_USE_CASE = "ADMIN_LOGIN_USE_CASE",
    ADMIN_REFRESH_USE_CASE = "ADMIN_REFRESH_USE_CASE",
    ADMIN_LOGOUT_USE_CASE = "ADMIN_LOGOUT_USE_CASE",
    ADMIN_REPOSITORY = "ADMIN_REPOSITORY",
}
