export enum AUTH_USER_TOKEN {
	USER_LOGIN_USE_CASE = "USER_LOGIN_USE_CASE",
	USER_REFRESH_USE_CASE = "USER_REFRESH_USE_CASE",
	USER_REGISTER_USE_CASE = "USER_REGISTER_USE_CASE",
	USER_VERIFY_OTP_USE_CASE = "USER_VERIFY_OTP_USE_CASE",
	USER_RESEND_OTP_USE_CASE = "USER_RESEND_OTP_USE_CASE",
	USER_LOGOUT_USE_CASE = "USER_LOGOUT_USE_CASE",
}
