export enum CERTIFICATE_TOKEN {
	CERTIFICATE_REPOSITORY = "CERTIFICATE_REPOSITORY",
	CREATE_CERTIFICATE_USE_CASE = "CREATE_CERTIFICATE_USE_CASE",
	GET_CERTIFICATES_USE_CASE = "GET_CERTIFICATES_USE_CASE",
	UPDATE_CERTIFICATE_USE_CASE = "UPDATE_CERTIFICATE_USE_CASE",
	DELETE_CERTIFICATE_USE_CASE = "DELETE_CERTIFICATE_USE_CASE",
}
