export enum CHAT_TOKEN {
	CHAT_REPOSITORY = "CHAT_REPOSITORY",
	SEND_MESSAGE_USE_CASE = "SEND_MESSAGE_USE_CASE",
	GET_HISTORY_USE_CASE = "GET_HISTORY_USE_CASE",
	GET_INBOX_USE_CASE = "GET_INBOX_USE_CASE",
	MARK_VIEWED_USE_CASE = "MARK_VIEWED_USE_CASE",
}
