export enum COMMON_TOKEN {
	PASSWORD_HASH = "PASSWORD_HASH",
	JWT_SERVICE = "JWT_SERVICE",
	REDIS_SERVICE = "REDIS_SERVICE",
	OTP_SERVICE = "OTP_SERVICE",
	UUID_SERVICE = "UUID_SERVICE",
	SESSION_VERIFICATION_SERVICE = "SESSION_VERIFICATION_SERVICE",
}
