export enum COMMON_TOKEN {
	PASSWORD_HASH = "PASSWORD_HASH",
	EMAIL_VALIDATOR = "EMAIL_VALIDATOR",
	JWT_SERVICE = "JWT_SERVICE",
	REDIS_SERVICE = "REDIS_SERVICE",
	OTP_SERVICE = "OTP_SERVICE",
	EMAIL_SERVICE = "EMAIL_SERVICE",
}
