export enum EDUCATION_TOKEN {
	EDUCATION_REPOSITORY = "EDUCATION_REPOSITORY",
	CREATE_EDUCATION_USE_CASE = "CREATE_EDUCATION_USE_CASE",
	GET_EDUCATIONS_USE_CASE = "GET_EDUCATIONS_USE_CASE",
	UPDATE_EDUCATION_USE_CASE = "UPDATE_EDUCATION_USE_CASE",
	DELETE_EDUCATION_USE_CASE = "DELETE_EDUCATION_USE_CASE",
}
