export enum JOB_TOKEN {
	JOB_REPOSITORY = "JOB_REPOSITORY",
	JOB_USE_CASE = "JOB_USE_CASE",
	CREATE_JOB_USE_CASE = "CREATE_JOB_USE_CASE",
	JOB_APPLICATION_REPOSITORY = "JOB_APPLICATION_REPOSITORY",
}
