export enum NOTIFICATION_TOKEN {
	NOTIFICATION_REPOSITORY = "NOTIFICATION_REPOSITORY",
	GET_NOTIFICATIONS_USE_CASE = "GET_NOTIFICATIONS_USE_CASE",
	MARK_NOTIFICATION_READ_USE_CASE = "MARK_NOTIFICATION_READ_USE_CASE",
	MARK_ALL_NOTIFICATIONS_READ_USE_CASE = "MARK_ALL_NOTIFICATIONS_READ_USE_CASE",
	GET_UNREAD_COUNT_USE_CASE = "GET_UNREAD_COUNT_USE_CASE",
}
