export enum PROJECT_TOKEN {
	PROJECT_REPOSITORY = "PROJECT_REPOSITORY",
	CREATE_PROJECT_USE_CASE = "CREATE_PROJECT_USE_CASE",
	GET_PROJECTS_USE_CASE = "GET_PROJECTS_USE_CASE",
	UPDATE_PROJECT_USE_CASE = "UPDATE_PROJECT_USE_CASE",
	DELETE_PROJECT_USE_CASE = "DELETE_PROJECT_USE_CASE",
}
