export enum USERS_TOKEN {
	USER_CREATE_USE_CASE = "USER_CREATE_USE_CASE",
	USER_REPOSITORY = "USER_REPOSITORY",
	USER_GET_USE_CASE = "USER_GET_USE_CASE",
	USER_UPDATE_USE_CASE = "USER_UPDATE_USE_CASE",
	USER_DELETE_USE_CASE = "USER_DELETE_USE_CASE",
	USER_GET_ALL_USE_CASE = "USER_GET_ALL_USE_CASE",
	USER_BLOCK_UNBLOCK_USE_CASE = "USER_BLOCK_UNBLOCK_USE_CASE",
}
