import type { IJobPersistenceMapper } from "@/application/interface/mappers/job/job-persistence.mapper";
import { JobEntity } from "@/domain/entity/job.entity";
import type { JobType } from "../db/mongodb/models/job.schema";
import { Injectable } from "@nestjs/common";

@Injectable()
export class JobPersistenceMapper implements IJobPersistenceMapper<JobEntity, JobType> {
	toMongo(data: JobEntity): JobType {
		return {
			_id: data.id ?? "",

			belongingCompany: data.belongingCompany,
			hiringCompany: data.hiringCompany,
			companyLogo: data.companyLogo,
			experienceType: data.experienceType,
			jobTitle: data.jobTitle,
			jobCategory: data.jobCategory,
			jobType: data.jobType,
			isNightShift: data.isNightShift,
			locationType: data.locationType,
			officeAddress: data.officeAddress,
			fieldArea: data.fieldArea,
			jobCity: data.jobCity,
			floorDetails: data.floorDetails,
			showFloorDetails: data.showFloorDetails,
			industry: data.industry,

			payType: data.payType,
			minSalary: data.minSalary,
			maxSalary: data.maxSalary,
			incentiveAmount: data.incentiveAmount,
			perks: data.perks,
			hasJoiningFee: data.hasJoiningFee,
			feeAmount: data.feeAmount,
			feeReason: data.feeReason,
			feeDetails: data.feeDetails,
			feePaymentTiming: data.feePaymentTiming,
			gender: data.gender,
			minAge: data.minAge,
			maxAge: data.maxAge,
			education: data.education,
			degreeSpecialization: data.degreeSpecialization,
			regionalLanguages: data.regionalLanguages,
			skills: data.skills,
			englishLevel: data.englishLevel,
			experience: data.experience,
			minExperience: data.minExperience,
			description: data.description,
			jobDescription: data.jobDescription,

			isWalkIn: data.isWalkIn,
			interviewAddress: data.interviewAddress,
			walkInStartDate: data.walkInStartDate,
			walkInEndDate: data.walkInEndDate,
			walkInStartTime: data.walkInStartTime,
			walkInEndTime: data.walkInEndTime,
			interviewInstructions: data.interviewInstructions,
			contactPreference: data.contactPreference,
			hrName: data.hrName,
			hrPhone: data.hrPhone,
			hrEmail: data.hrEmail,
			otherRecruiterName: data.otherRecruiterName,
			otherRecruiterWhatsapp: data.otherRecruiterWhatsapp,
			otherRecruiterEmail: data.otherRecruiterEmail,
			canCandidateContact: data.canCandidateContact,
			whatsappAlerts: data.whatsappAlerts,

			selectedPlan: data.selectedPlan,

			company_id: data.company_id,
			posted_by: data.posted_by,
			status: data.status,
			is_published: data.is_published,
			created_at: data.created_at,
			updated_at: data.updated_at,
		} as unknown as JobType;
	}

	async fromMongo(data: JobType): Promise<JobEntity> {
		return JobEntity.create({
			id: data._id.toString(),

			belongingCompany: data.belongingCompany || "",
			hiringCompany: data.hiringCompany || "",
			companyLogo: data.companyLogo || "",
			experienceType: data.experienceType || "",
			jobTitle: data.jobTitle || "",
			jobCategory: data.jobCategory || "",
			jobType: data.jobType || "",
			isNightShift: data.isNightShift || false,
			locationType: data.locationType || "",
			officeAddress: data.officeAddress || "",
			fieldArea: data.fieldArea || "",
			jobCity: data.jobCity || "",
			floorDetails: data.floorDetails || "",
			showFloorDetails: data.showFloorDetails || false,
			industry: data.industry || [],

			payType: data.payType || "",
			minSalary: data.minSalary || "",
			maxSalary: data.maxSalary || "",
			incentiveAmount: data.incentiveAmount || "",
			perks: data.perks || [],
			hasJoiningFee: data.hasJoiningFee || "No",
			feeAmount: data.feeAmount || "",
			feeReason: data.feeReason || "",
			feeDetails: data.feeDetails || "",
			feePaymentTiming: data.feePaymentTiming || "",
			gender: data.gender || "",
			minAge: data.minAge || "",
			maxAge: data.maxAge || "",
			education: data.education || "",
			degreeSpecialization: data.degreeSpecialization || [],
			regionalLanguages: data.regionalLanguages || [],
			skills: data.skills || [],
			englishLevel: data.englishLevel || "",
			experience: data.experience || "",
			minExperience: data.minExperience || "",
			description: data.description || "",
			jobDescription: data.jobDescription || "",

			isWalkIn: data.isWalkIn || false,
			interviewAddress: data.interviewAddress || "",
			walkInStartDate: data.walkInStartDate || "",
			walkInEndDate: data.walkInEndDate || "",
			walkInStartTime: data.walkInStartTime || "",
			walkInEndTime: data.walkInEndTime || "",
			interviewInstructions: data.interviewInstructions || "",
			contactPreference: data.contactPreference || "",
			hrName: data.hrName || "",
			hrPhone: data.hrPhone || "",
			hrEmail: data.hrEmail || "",
			otherRecruiterName: data.otherRecruiterName || "",
			otherRecruiterWhatsapp: data.otherRecruiterWhatsapp || "",
			otherRecruiterEmail: data.otherRecruiterEmail || "",
			canCandidateContact: data.canCandidateContact || "No",
			whatsappAlerts: data.whatsappAlerts || "",

			selectedPlan: data.selectedPlan || "",

			company_id: data.company_id || "",
			posted_by: data.posted_by || "",
			status: data.status || "OPEN",
			is_published: data.is_published || false,
			created_at: data.created_at || "",
			updated_at: data.updated_at || "",
		});
	}
}
